language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules

before_install:
  - npm update
install:
  - npm install
script:
  - npm run test

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"